version: "3.8"

services:
  db:
    restart: always
    container_name: db
    image: postgres:alpine
    volumes:
      - ./db/db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - surveys_net

  surveys:
    restart: always
    build: ./app
    container_name: surveys
    volumes:
      - ./app:/app
#    command: bash -c "python manage.py collectstatic --noinput
#      && gunicorn stubla.wsgi:application --workers ${WORKERS_NUM} --timeout ${TIMEOUT} --bind 0.0.0.0:8000"
    command: bash -c "sleep 20 && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - surveys_net

networks:
    surveys_net:
        driver: bridge
