version: "3.8"

services:
  db:
    restart: always
    container_name: db
    image: postgres:alpine
    volumes:
      - ./db/db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env_exapmle
    networks:
      - surveys_net

  surveys:
    restart: always
    build: ./app
    container_name: surveys
    volumes:
      - ./app:/app
    command: bash -c "python manage.py makemigrations
                      && python manage.py migrate
                      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - .env_exapmle
    depends_on:
      - db
    networks:
      - surveys_net

networks:
    surveys_net:
        driver: bridge
