# Generated by Django 2.2.10 on 2021-05-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='takensurvey',
            name='anonymously',
            field=models.BooleanField(default=False),
        ),
    ]
